// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7GStJmAYdmm5g2c3EGvZEIFfYjt4K4ZM',
    appId: '1:984546662324:web:defd1ac89f8a004d7f84e1',
    messagingSenderId: '984546662324',
    projectId: 'enebla-be035',
    authDomain: 'enebla-be035.firebaseapp.com',
    storageBucket: 'enebla-be035.appspot.com',
    measurementId: 'G-RQ5H63N9J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlkCUuVN4RdM0dEbFqp-AP65fIre9dxMY',
    appId: '1:984546662324:android:c0dbcd97cf62fa177f84e1',
    messagingSenderId: '984546662324',
    projectId: 'enebla-be035',
    storageBucket: 'enebla-be035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG5G6K7FghlMcKnUbVfzwgIN60WcX_W5o',
    appId: '1:984546662324:ios:a8ad9483cde82df17f84e1',
    messagingSenderId: '984546662324',
    projectId: 'enebla-be035',
    storageBucket: 'enebla-be035.appspot.com',
    iosBundleId: 'com.example.enebla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG5G6K7FghlMcKnUbVfzwgIN60WcX_W5o',
    appId: '1:984546662324:ios:10b94b59046a8e947f84e1',
    messagingSenderId: '984546662324',
    projectId: 'enebla-be035',
    storageBucket: 'enebla-be035.appspot.com',
    iosBundleId: 'com.example.eneblaNew.RunnerTests',
  );
}
